### PR TITLE
Convert Exercises in Inventory Dynamic to JAX

### LINKED ISSUE #4: Add a JAX version of the inventory lecture
Repeat the coding part of https://python.quantecon.org/inventory_dynamics.html but using JAX.

Reference https://python.quantecon.org/inventory_dynamics.html at the start, so the reader can see the original problem and where it comes from.

Start with the key equations and then redo the simulations in JAX.

Add another exercise that request some heavy computation,.

### PR DESCRIPTION
**Pull request by HumphreyYang**
This PR resolves #4.

### CODE REVIEW

**Comment by HumphreyYang** [comment]
Hi @jstac, 

I applied the same principle for `for` loop version as I had in the Kesten Processes lecture. The speed for the `for` loop version is almost comparable to the compilation time of the `lax.scan` version here. Although the `for` loop version will have slightly more overhead when it is run for the second time.

**Comment by jstac** [comment]
Great job @HumphreyYang .  Very nice.

Please remove the in work label when ready.

@HengchengZhang or @chappiewuzefan please review just to have another set of eyes go through this.

**Comment by HumphreyYang** [comment]
Hi @HengchengZhang and @chappiewuzefan, 

This is now ready for review. I have updated the update function so that it is faster, and presumably more memory efficient. 

Please let me know if there is anything that needs to be changed.

**Comment by HengchengZhang** [comment]
Many thanks @HumphreyYang for this awesome lecture, I'll do it later.

**Comment by jstac** [comment]
@HengchengZhang and @chappiewuzefan , it would be good to get this merged.

Plase also fix the conflict in to toc file.

**Comment by chappiewuzefan** [comment]
when I commented this line `_, key = random.split(key)` 
and generated the below graph:
image
is it necessary to add a comment to indicate that we need to generate new key every time for generating Z?

**Comment by HumphreyYang** [comment]
Many thanks @chappiewuzefan, nice point.

It is mentioned in [JAX lecture](https://python-programming.quantecon.org/jax_intro.html#random-numbers), so I think it may be safe to leave it out. Otherwise, it will need to be specified everywhere (CC @jstac).

**Comment by HumphreyYang** [comment]
Hi @jstac,

This PR is ready for your review. The lecture on Kesten Processes is also ready [here](https://github.com/QuantEcon/lecture-jax/pull/29).

Many thanks in advance.

**Comment by jstac** [comment]
Many thanks @HumphreyYang .

I have some small requests:

1. Please adjust capitalization of headings as per https://manual.quantecon.org/styleguide/writing.html
2. I find the approach of using a closure in `shift_firms_forward` elegant but it goes against a the pure functional style of JAX, since the nested jit compiled function is not pure.  Please take `update_X` out and make it a pure function.
3. Please have separate subsections for the for loop and `lax.scan` approaches.  
4. Please write in a more neutral way about `lax.scan`, rather than implying it is recommended.  Instead, just describe it's costs and benefits.  (There will be many cases where the `lax.scan` approach causes an out of memory error.  But for smaller runs it's faster.)
5. In `plot_kde`, please give a more complete example, with an actual plot.
6. Please refer back to the original lecture at the start.

**Comment by jstac** [comment]
Many thanks @HumphreyYang

**Pull request merged**
