### PR TITLE
Opt Savings: Use Vectorized function instead of broadcasting

### PR DESCRIPTION
**Pull request by Smit-create**

### CODE REVIEW

**Comment by Smit-create** [comment]
Hi @jstac,

I completed using `vmap` everywhere possible instead of `reshape`. The results on the PR are:
```
HPI completed in 0.03335309028625488 seconds.
VFI(jax not in succ) completed in 1.0069973468780518 seconds.
OPI completed in 0.3129911422729492 seconds.
```

And on the published lecture: https://jax.quantecon.org/opt_savings.html
```
HPI completed in 0.03399658203125 seconds.
VFI(jax not in succ) completed in 0.90895676612854 seconds.
OPI completed in 0.3122248649597168 seconds.
```

So, not much difference between HPI and OPI, but VFI got is about 11% slower on this branch.

**Comment by jstac** [comment]
Many thanks @Smit-create , this is very nicely done.

But in the interests of readability, would it be possible to have just two functions, `B` and `B_vec`, where `B` gets vectorized by `vmap`?  I prefer it that `B` gives a very clear and readable description of the right hand side of the Bellman equation, and then all of the vectorization  takes place on the outside to create `B_vec`.

This requires removing the intermediate functions like `compute_c`.    I'm not sure if it's possible.

**Comment by Smit-create** [comment]
Many thanks for the review @jstac. That's a good idea. I'll try to look into that in a new PR so that we can compare this and the new one.

**Comment by jstac** [comment]
Already implemented

**Pull request closed without merging**
