### PR TITLE
MAINT: Harmonise GPU admonition, remove backend checks + add nvidia-smi

### PR DESCRIPTION
**Pull request by mmcky**
This PR:

- [x] adds GPU admonition from https://manual.quantecon.org/styleguide/code.html#jax
- [x] removes code snippets for checking the gpu backend (and added to `status.md`)
- [x] add `nvidia-smi` to make hardware more visible to readers (testing in `wealth_dynamics` lecture)

cc: @jstac

- [x] review build in the morning before merging

### CODE REVIEW

**Comment by mmcky** [comment]
@HengchengZhang is there a way to fix 

```
(           intro: line   18) broken    https://quantecon.org/projects/#filter=lecture - Anchor 'filter=lecture' not found
```

I added this link to replace the old one on the `intro` page but it uses an anchor to run a query.

**Comment by HengchengZhang** [comment]
Hi @mmcky, I'm not sure where this link should be directed to. Is that https://quantecon.org/python-lectures/?

**Comment by mmcky** [comment]
> Hi @mmcky, I'm not sure where this link should be directed to. Is that https://quantecon.org/python-lectures/?

Sorry @HengchengZhang -- I wasn't clear. The link is correct but needs the anchor. Will that cause problems with the sphinx linkchecker from your investigations?

**Comment by mmcky** [comment]
@jstac as this impacts widely I will merge this now. I'll help with any merge conflict on #49

**Comment by HengchengZhang** [comment]
That should not be the problem with link checker, our QuantEcon links only returns error when it's actually broken.

So I think there's something wrong with this anchor or the use of anchor?

**Pull request merged**
