### PR TITLE
MAINT: use Github based GPU instance

### PR DESCRIPTION
**Pull request by mmcky**
This PR makes use of the `Tesla T4` instance now available on `GitHub Actions` as a beta instance. 

- [x] uses `github actions` supplied instances
- [x] deploys from github containers for our docker environment to speed up builds

this migrates

- [x] `ci`
- [x] `publish`
- [x] `cache`

to run on GitHub actions.

### CODE REVIEW

**Comment by mmcky** [comment]
- [ ] re-enable build cache

**Comment by mmcky** [comment]
The results between `EC2` (left) and `GitHub Actions` (right)

Screenshot 2024-05-09 at 4 00 54 PM

**Comment by mmcky** [comment]
Just triggered a new `publish` so we are comparing like for like.

**Comment by kp992** [comment]
This is interesting @mmcky! Now since we are using GA's GPU for trial, shall we compare the costs that we were having through AWS and now on GA -- maybe need to figure out how are we going to compare the costs since I believe it will depend on the frequency of commit push?

**Comment by mmcky** [comment]
> This is interesting @mmcky! Now since we are using GA's GPU for trial, shall we compare the costs that we were having through AWS and now on GA -- maybe need to figure out how are we going to compare the costs since I believe it will depend on the frequency of commit push?

that's right @kp992 -- the pricing is:

| Service | Cost | Units |
|---------|---------------|---------------|
| EC2 (`p2.xlarge`) |  $0.90 | per instance Hour |
| GA (`Ubuntu GPU 4-core`) |  $0.07 | per minute |

So if we have a `10 minute` job then

| Service | Cost |
|---------|---------------|
| EC2 (`p2.xlarge`) |  $0.90 |
| GA (`Ubuntu GPU 4-core`) |  $0.70 | 

so the pricing really depends on the frequency of long runs vs short runs. Honestly (while the per hour price on GA is a LOT higher, I think it will work out to be pretty similar).

**Comment by mmcky** [comment]
@kp992 this is the `like-for-like` time comparisons now with the current `live` site. 

Screenshot 2024-05-10 at 9 08 40 AM

still an interesting mix of performance differences. 

**Machine Details:**

Name | GPUs | vCPUs | RAM (GiB) | NetworkBandwidth | Price/Hour* | RI Price / Hour**
-- | -- | -- | -- | -- | -- | --
p2.xlarge | 1 | 4 | 61 | High | $0.900 | $0.425

**Comment by mmcky** [comment]
- [ ] remove the docker container layer to see if that speeds up compute times

**Comment by mmcky** [comment]
Currently the kernel is dying when installing directly onto the `vm` provided by github (rather than using our docker container). IT would be quicker and more efficient to get this route working.

**Comment by kp992** [comment]
Thanks @mmcky, are we moving forward with moving to Github Actions VM for all our repos using AWS?

**Comment by mmcky** [comment]
> Thanks @mmcky, are we moving forward with moving to Github Actions VM for all our repos using AWS?

I would like to if we can -- as that is less to maintain. But currently I am getting issues with kernels dying which suggest that `jax` install isn't working properly (without a container).

**Comment by mmcky** [comment]
- [ ] this PR https://github.com/QuantEcon/lecture-python-intro/pull/441 on the intro lecture series suggests that the docker container provided by google is not up to date making it hard to use as a test.

**Comment by mmcky** [comment]
The driver versions under docker are:

```
NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.3    
``` 

and when using the native VM

```
 NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2  
```

so the CUDA version is likely causing the issue?

**Comment by mmcky** [comment]
@kp992 any ideas on why the jupyter kernel is dying when running directly on the VM but the docker container is OK?

- [ ] @mmcky can we host the docker container on github to speed up the compute?

**Comment by mmcky** [comment]
@mmcky working on using `github containers` to store the docker container here
https://github.com/QuantEcon/lecture-python.docker/pull/4

**Comment by mmcky** [comment]
@kp992 the fetch from github containers is about 10min. That is pretty good right?

**Comment by mmcky** [comment]
@kp992 it looks like these instances may have CUDA=12.3 installed. Our docker is configured for CUDA=12.5 so there are a lot of `ptax` warnings. We may need to adjust the Docker container to enable this context (or upgrade CUDA drivers). I think CUDA upgrades would require a reboot but looking into it.

**Comment by mmcky** [comment]
@kp992 looks like the newer CUDA driver is working. Will post a speed comparison with the current live site once I get the preview.

**Comment by mmcky** [comment]
@jstac and @kp992 here are the latest results moving our computations to the GitHub based GPU instance. LHS = current live site (built on EC2) and RHS = this PR (built on Github + using CUDA=12.5 driver). Many times are improved except for Wealth Dynamics (@kp992 would you mind reviewing this lecture to see why this might be?)

Screenshot 2024-06-11 at 4 10 39 PM

**Comment by jstac** [comment]
Thanks @mmcky , good to know.

**Comment by kp992** [comment]
Thanks @mmcky, this looks great. I can look at the wealth dynamics timings difference.

**Comment by mmcky** [comment]
thanks @jstac and @kp992. I am doing one final round of review on this and then I will migrate to use github instances for this lecture series as well.

**Comment by mmcky** [comment]
- [ ] check this closely as the `nvidia-smi` is reporting and the docker container is using  `CUDA=12.5`

NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 12.3

**Comment by mmcky** [comment]
@kp992 I think this is ready. If you can cast your eye over it one more time then I'll merge.

**Review by kp992 — APPROVED** [review]
Looks perfect! Thanks @mmcky

**Pull request merged**
