### PR TITLE
Add spellcheck CI job

### PR DESCRIPTION
**Pull request by kp992**

### CODE REVIEW

**Comment by mmcky** [comment]
@kp992 can you update me on the status here. Do you like this extension? Should we invest in it -- I suspect we will need to add some training / dictionary additions for our domain etc.

**Comment by kp992** [comment]
@mmcky, the idea is good and works here. There a few disadvantages from this -- too many false positives, there isn't any way to differentiate between a simple english word/python variable and so the CI will get very noisy. Detecting true positive from a list of so many false positives is even more hard.

**Comment by mmcky** [comment]
thanks @kp992 our link checker already produces some `rare` false positives -- but that really reduces the amount of attention paid to it so I recommend we take this offline and do some more testing to get solve the `false` positive rate before we think of rolling this out.

**Comment by mmcky** [comment]
sounds like the `python` spell check functionality is not available as it wouldn't understand myst directives

**Comment by kp992** [comment]
That's right @mmcky. Please feel free to modify this or close this.

**Comment by mmcky** [comment]
thanks @kp992 I think we can do additional testing so I will close this for now.

**Pull request closed without merging**
