### PR TITLE
minor_edits

### PR DESCRIPTION
**Pull request by shlff**
Hi @jstac this PR fixes some typos in the lecture ``ifp_egm``.

### CODE REVIEW

**Comment by jstac** [comment]
@mmcky , I surprised that this is failing.  The edits seem innocuous.

**Comment by jstac** [comment]
ah, perhaps it's because your link goes across multiple lines @shlff

**Comment by mmcky** [comment]
> @mmcky , I surprised that this is failing. The edits seem innocuous.

It is just the `anchor` issue causing the linkchecker to fail.

**Review by mmcky — APPROVED** [review]

**Comment by jstac** [comment]
Thanks @shlff , mergine.

**Pull request merged**
