### PR TITLE
Add a lecture on asset pricing

### PR DESCRIPTION
**Pull request by jstac**
Adds a lecture on asset pricing

### CODE REVIEW

**Comment by jstac** [comment]
@Smit-create , would you mind to quickly look over this lecture and see if you have comments?

The mathematical details are rather long, but you can skip to the equations and the code.

**Comment by Smit-create** [comment]
Thanks @jstac. I'll look into it tonight or tomorrow morning.

**Comment by mmcky** [comment]
@Smit-create can you also:

- [ ] fix duplicate labels 

```
/__w/lecture-jax/lecture-jax/lectures/markov_asset.md:556: WARNING: duplicate label of equation eq:neweqn103, other instance in markov_asset
/__w/lecture-jax/lecture-jax/lectures/markov_asset.md:: CRITICAL: Duplicate ID: "equation-eq-neweqn103".
/__w/lecture-jax/lecture-jax/lectures/markov_asset.md:592: WARNING: duplicate label of equation eq:neweqn104, other instance in markov_asset
/__w/lecture-jax/lecture-jax/lectures/markov_asset.md:: CRITICAL: Duplicate ID: "equation-eq-neweqn104".
```

and 

- [ ] add quantecon package from the execution error report

```
ModuleNotFoundError: No module named 'quantecon'
```

**Comment by Smit-create** [comment]
There's a failure in `test_stability` due to the following reason:
```console
NotImplementedError: Nonsymmetric eigendecomposition is only implemented on the CPU backend. If your matrix is symmetric or Hermitian, you should use eigh instead.

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.
```

This is also mentioned in their docs: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.linalg.eig.html

**Comment by jstac** [comment]
@Smit-create Many thanks for adding that routine!

I've made some small edits but broken the build.  I don't have time to continue right now --- if you can look at it again that would be great.

BTW, one nice thing about that power method is that it can be applied to any linear operator, not just a matrix.  So, in principle, we can apply it to the memory-efficient `H_operator` in the Efficient JAX section.  But some modifications to the power iteration code would be required.

**Comment by Smit-create** [comment]
@jstac thanks. The build is fixed.

> BTW, one nice thing about that power method is that it can be applied to any linear operator, not just a matrix. So, in principle, we can apply it to the memory-efficient H_operator in the Efficient JAX section. But some modifications to the power iteration code would be required.

Do you want to make these changes in this PR? or do you want to open an issue to track this and fix it in a new PR?

**Comment by jstac** [comment]
Thanks for fixing the build @Smit-create 

> Do you want to make these changes in this PR? or do you want to open an issue to track this and fix it in a new PR?

I've opened an issue for this --- see #63

**Pull request merged**
