### PR TITLE
Split the equation 4.18 into 2 lines

### PR DESCRIPTION
**Pull request by Smit-create**
#110 

Split 4.18 into 2 lines

### CODE REVIEW

**Comment by Smit-create** [comment]
Thank you @jstac for the review. I have used `multline` in 4.18 and 4.20.

**Comment by shlff** [comment]
Thanks @Smit-create and @jstac . 

I found the newest deployment still gives us an error for eq 4.18 and one before 4.21. Please find it here:
Screenshot 2023-09-15 at 1 34 17 pm

I will investigate the latex code.

**Comment by shlff** [comment]
The issue has been fixed: 

https://6503e886a66e2154a98cb37a--incomparable-parfait-2417f8.netlify.app/markov_asset#equation-eq-neweqn102

**Comment by jstac** [comment]
Many thanks @Smit-create and @shlff

**Pull request merged**
