### PR TITLE
Use callback in `successive_approx`

### PR DESCRIPTION
**Pull request by kp992**
Use callback in `successive_approx` and create JAX-jitted `successive_approx`

### CODE REVIEW

**Comment by kp992** [comment]
@jstac This PR adds callback in successive_approx, and removes its jitting. Do you think this is good?

**Comment by jstac** [comment]
Thanks @kp992 .  I think this style is consistent with other solution methods, such as https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.optimize.minimize.html

The function that solves the problem receives as arguments the function that it acts on, an initial guess, and other remaining parameters.

Is it necessary to remove jitting?

Does performance change by much?

**Comment by kp992** [comment]
Thanks for the review @jstac!

I have added the `successive_approx_jax` with jitting and also having the same signature as previously (i.e. Operator callback). Performance wise its better than the one which wasn't using jitting.

**Comment by jstac** [comment]
Thanks @kp992 !

Can you tell me why this works for the new version: `static_argnums=(0,)` .

This means that the callable is a "compile-time constant"?  I don't get it...

**Comment by kp992** [comment]
There is also one more approach using https://github.com/google/jax/issues/1443#issuecomment-1527813792. If you want, I can try this too.

**Comment by jstac** [comment]
This is perfect, thanks @kp992 .  Let's stick with this one.

**Pull request merged**
