### PR TITLE
Add cake_eating lecture

### LINKED ISSUE #8: Add a JAX version of cake eating --- Continuous state DP with JAX benchmark lecture!
Add a JAX version of https://python.quantecon.org/cake_eating_numerical.html

This will be an important benchmark lecture because we want to get the approach right in a very simple dynamic programming problem with a continuous state space before we tackle the harder ones.

These issues have been discussed by @jstac and @Smit-create in https://github.com/QuantEcon/smit_dp_jax/issues/2

(@Smit-create , can you please add others to this repo so that we can all view that issue?)

Let's all solve this together and make sure we are happy with our approach before we go further.

### PR DESCRIPTION
**Pull request by Smit-create**
Fixes #8

### CODE REVIEW

**Comment by Smit-create** [comment]
@mmcky Can you please check the GH actions?

**Comment by mmcky** [comment]
> @mmcky Can you please check the GH actions?

Thanks @Smit-create not sure what happened but I restarted `GH actions` and it seems to be running now.

**Comment by Smit-create** [comment]
@jstac I have added the complete JAX code on cake eating lecture. I will still need to add some notes and some modify some docstrings but the code part is almost done. Do you want me to add the `numpy` code and compare time results? or keep it as it is right now? It's pretty fast even with brute force as I have done `jitting` and `vmap` wherever possible to make it robust.

**Comment by jstac** [comment]
This is great @Smit-create!  Nice work.

Yes, please do a time comparison.

You might need to increase the grid size a bit to make the comparison interesting.  (But too large will seem strange.)

**Comment by Smit-create** [comment]
@jstac I have added a numpy section directly from the original lecture and we have the following results with brute force:
```
>> jax_time, np_time
(3.9867148399353027, 10.5426607131958)
```

The lecture will still require many clean-ups and wanted to know your opinions on what to keep in the lecture (section design and lecture flow.)

**Comment by jstac** [comment]
Many thanks @Smit-create .

Please make the following changes:

- `x_grid` increases in size to 200.
- `c_grid` is a fixed grid created only once of the form `np.linspace(x_grid_min, x_grid_max, x_grid_size * 2)`
- The utility function `u` returns just `c ** (1 - cem.γ)) / (1 - cem.γ)`  (there is no test for the log case).
- The `maximize` function can be eliminated and that logic can be put inside the function `T`.
- Please quickly check the docstrings.  It might be helpful to explain what the shapes of the variables will be in `state_action_value`.

**Comment by Smit-create** [comment]
> * `c_grid` is a fixed grid created only once of the form `np.linspace(x_grid_min, x_grid_max, x_grid_size * 2)`

This wasn't producing good results so I changed it to `np.linspace(x_grid_min, x_grid_max, x_grid_size * 100)`

**Comment by jstac** [comment]
This is perfect @Smit-create , great work.

**Pull request merged**
