### PR TITLE
Shortest path JAX

### PR DESCRIPTION
**Pull request by Smit-create**
#7

### CODE REVIEW

**Comment by Smit-create** [comment]
@jstac This is ready for a review.

**Comment by jstac** [comment]
Great work @Smit-create , very nice.

Could you please add as the second sentence "Please see that lecture for all background and notation."

Also, could you please start with a version using an ordinary while look, where you just replace `np` with `jnp`.  Then explain it can be further accelerated with `jax.lax.while_loop`.

"The extra acceleration is due to the fact that the entire operation can be optimized by the JAX compiler and launched as a single kernel on the GPU."

Perhaps also mention that large speed gains won't be realized unless the shortest path problem is relatively large.

**Review by jstac — APPROVED** [review]
Approved subject to small requests posted above.

**Comment by Smit-create** [comment]
Thanks, @jstac for the review. I have added the Python while loop version and with the same small example, JAX is almost 100 times faster. Please feel free to merge this with final approval.

**Comment by jstac** [comment]
Perfect, thanks @Smit-create .  Merging.

**Pull request merged**
