### PR TITLE
Update lecture 7

### PR DESCRIPTION
**Pull request by sidd3888**
- Have removed a block of code that runs the `lax.scan` implementation before it is defined.
- Fixed a typo that wrongly runs the `for` loop implementation after JIT compilation of the `lax.scan` version.
- Stated the initial parameters to be used (inferred from solution) for exercise 7.2.

### CODE REVIEW

**Comment by jstac** [comment]
@mmcky , could you please have a quick look at this and see why it's failing?

**Comment by mmcky** [comment]
thanks @sidd3888 and @jstac looking into this now. I appears there is an issue with security tokens and talking with EC2.

**Comment by mmcky** [comment]
OK So it appears that GitHub doesn't expose repo secrets in GitHub actions when the PR is originating from a fork. 

@sidd3888 can I give you collaborator access to this repo and you setup a local branch and PR?

**Comment by sidd3888** [comment]
Sure, I'll add the changes here then.

**Pull request closed without merging**
