### PR TITLE
 TEST: use Github based GPU instance for CI 

### PR DESCRIPTION
**Pull request by kp992**
Built on top of #181 

Use Github Actions GPU instance on CI.

### CODE REVIEW

**Comment by kp992** [comment]
Thanks @mmcky, I will try to setup it and check.

**Comment by mmcky** [comment]
@kp992 thanks for trying some things out however [2ff9298](https://github.com/QuantEcon/lecture-jax/pull/183/commits/2ff9298addefc6ef318f4737e80289f581dcbfe8) still uses a docker container which is not required. If you take a look at most of our github actions workflows then you can see we don't use a docker container in most of them. That is what I am proposed as the docker download takes a long time.

**Comment by kp992** [comment]
Thanks @mmcky, I also trying to find that approach. I was verifying that we somehow need to install cuda. One of the approach is through docker as seen. I will try with conda.

**Comment by kp992** [comment]
Hmm, its not working. The best way I think is to use the docker that you have made (existing `main` branch CI) and cache it. Since we are not updating the image frequently, that should be easier to manage. How does that sound?
Ref: https://github.com/marketplace/actions/build-docker-images-using-cache

**Comment by mmcky** [comment]
> Hmm, its not working. The best way I think is to use the docker that you have made (existing `main` branch CI) and cache it. Since we are not updating the image frequently, that should be easier to manage. How does that sound? Ref: https://github.com/marketplace/actions/build-docker-images-using-cache

@kp992 can we build the docker image on GitHub actions and then cache it from another repo? 

I build the image https://github.com/quantecon/lecture-python.docker and then sync it to docker hub. But if we can save it as an asset in QuantEcon GitHub then we can pull it locally which should be quicker.

**Comment by kp992** [comment]
I am trying to do the same, but, for a single repo. For example check the last two commits of this PR which have Github actions run: https://github.com/QuantEcon/lecture-jax/actions/runs/9258083875/job/25555094247 (first run) and https://github.com/QuantEcon/lecture-jax/actions/runs/9287258102/job/25555816581(second run). First run took about 13m and the second one about 11m so we are saving 2 mins. I think we can also optimize the Anaconda setup by including it in the docker itself which you have done in https://github.com/quantecon/lecture-python.docker. I will try it and see the results.

**Comment by kp992** [comment]
https://github.com/QuantEcon/lecture-jax/actions/runs/9339691234/job/25704378502 took about 34 mins to load our docker which is very high compared to pulling nvidia docker and setting up conda differently which took about 13 mins.

**Comment by kp992** [comment]
@mmcky How does this commit https://github.com/QuantEcon/lecture-jax/pull/183/commits/9ee6f2141ed36ca31e7e2814ff86078b45921eb2 look? Should we go ahead with nvidia cuda docker  (cache enables) and Anaconda setup separately?

**Comment by mmcky** [comment]
> https://github.com/QuantEcon/lecture-jax/actions/runs/9339691234/job/25704378502 took about 34 mins to load our docker which is very high compared to pulling nvidia docker and setting up conda differently which took about 13 mins.

@kp992 I suspect the nvidia docker is cached as a I think they are similar GB sizes. I was wantign to see if we can cache our docker container as a GitHub asset to improve on this. Do you know if this is possible -- we build that container on github and then send it to dockerhub but a local asset might be a better way to go if there is a local registry.

**Comment by kp992** [comment]
Hmm, I am not aware of anything like that. I guess Github provides about 10 GB of caching where we can use our pulled docker container to be saved in .zip file and pull it whenever we run it next time. Since, docker won't be updated very frequently, it is maintainable too.

**Comment by mmcky** [comment]
@kp992 rather than managing cache objects ourselves (as they usually expire after 1 month of inactivity)  I was thinking of using the github registry for the docker container. Is this feasible?

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by mmcky** [comment]
@kp992 I think this can now be closed in favour of #181

**Pull request closed without merging**
